magic_8_ball = [
            "It is certain.",
            "It is decidedly so.",
            "Without a doubt.",
            "Yes definitely.",
            "You may rely on it.",
            "As I see it, yes.",
            "Most likely.",
            "Outlook good.",
            "Yes.",
            "Signs point to yes.",
            "Reply hazy, try again.",
            "Ask again later.",
            "Better not tell you now.",
            "Cannot predict now.",
            "Concentrate and ask again.",
            "Don't count on it.",
            "My reply is no.",
            "My sources say no.",
            "Outlook not so good.",
            "Very doubtful.",
            "As if we don't have this in the bag.",
            "Scouting could be wrong, no offense.",
            "IDK, ask Art?",
            "Buy Dottie a pizza.",
            "Guaranteed 0 diff.",
            "Fuck the mets.",
            "Don't swipe right, it's your cousin!",
            "This is giving me a headache.",
            "That sounds awful.",
            "Break out the champagne!",
            "Even a blind squirrel finds a nut sometimes.",
            "Go call your mother.",
            "Why do you think a fake version of a piece of floating plastic has the answers you're looking for?",
            "Can't you figure that out yourself?",
            "You sick bastard.",
            "Outlook not so good. Please use a different email client",
            "Do or do not. There is no try.",
            "What about second breakfast?",
            "Barbecue sauce.",
            "That would be so fetch!",
        ]

complaint_warning = "Thanks for submitting a complaint! All complaints are submitted anonymously and your name will be hidden from moderators, however the bot does have the ability to allow mods to send a response. Please note that in the interest of keeping this system from being abused, mods do have the ability to display your name. Doing so requires explicit approval from all five moderators, and will alert you immediately should this action be taken."
